title: ICLR 2024 Workshop on AI4DifferentialEquations in Science
description: ""

timezone: Central European Standard Time

navigation:
  Home: "/AI4DiffEqtnsInSci"
  Call for Papers: "/AI4DiffEqtnsInSci/cfp"
  # Challenge: "https://github.com/geomstats/challenge-iclr-2022"
  # Accepted Papers: "/papers"
  Speakers: "/AI4DiffEqtnsInSci/speakers"
  Organizers: "/AI4DiffEqtnsInSci/organizers"
  Schedule: "/AI4DiffEqtnsInSci/schedule"
  # Past Events: "/past"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
